-- INSERT INTO users (username, fname, lname)
-- VALUES ('imedellin', 'isaias', 'medellin');
-- INSERT INTO users (username, fname, lname)
-- VALUES ('jgomez', 'Joe', 'Gomez');
-- INSERT INTO user_bmi (userID, age, height, weight)
-- VALUES (1, 27, 67, 250.5);